#!/bin/bash

# VARS #
version=0.0.1
modified=01/Nov/2020

# NULL INPUT CAPTURE #
if [ -z $1 ]; then
   echo "You don't appear to have entered a value for the fqdn"
   echo "use 'get help' for syntax assistance"
   exit 1;
fi

# ABOUT #
if [ $1 == 'version' ]; then
   echo "==========================================================="
   echo "'cxn' version $version written and developed by Graham Trueman"
   echo "==========================================================="
   exit 1;
fi

# HELP #
if [ $1 == 'help' ]; then
   clear
   echo "========"
   echo "CXN tool"
   echo "========"
   echo ""
   echo "Syntax: 	cxn $env $server  Makes a connection attempt"
   echo "               cxn $env key      Checks which ssh key is in use"
   echo ""
   echo "This script provides a quick ssh connection to a known linux server."
   echo "Assumptions are that a valid key and active firewall or vpn connection are available."
   echo ""
   echo ""
   echo "=========================="
   echo "'cxn' version: $version"
   echo "Last modified: $modified"
   echo "=========================="
   echo ""
   exit 1;
fi

# CLEAN DIRECTORY #
if [ $1 == 'clean' ] ; then
  echo "Cleaning leftover files from previous script execution."
  exit 1;
fi

# ADDITIONAL INPUT MISSING CAPTURE #

if [ -z $2 ]; then
   echo "You don't appear to have entered "
   echo "use 'get help' for syntax assistance"
   exit 1;
fi


# SCRIPT #

