#!/bin/bash
# VARS #
version=1.1.0
modified="4 November 2020"

mboxes=38 # Can edit the number of M boxes here
pkey="/auth/keys/master-vpc-keypair-us-east-1.pem" # Replace local pem key here

# NULL INPUT CAPTURE #
if [ -z $1 ]; then
   echo "Missing option - nothing to execute"
   echo "Usage: jb (start|stop|restart|list|version|help)"
   exit 1;
fi

# ABOUT #
if [ $1 == 'version' ]; then
   echo "============================================================="
   echo "jb version $version written and developed by Graham Trueman"
   echo "last modified: ${modified}"
   echo "============================================================="
   exit 1;
fi

# JBOSS RANGE
if [[ $1 == 'range' ]]; then
  echo "Current range set to $mboxes"
  echo "Change manually, and commit permanent range increases to the repository."
  exit 1;
fi

# JBOSS LOOP LIST #
if [[ $1 == 'list' ]]; then
	i=0
  if [[ -z $2 ]]; then
    i=0
  fi
  if [[ $2 -ge $i ]]; then
    i=$[$2-1]
  fi
  # to
  if [[ -z $3 ]]; then
    echo "Running to end"
  fi
  if [[ $3 -ge $mboxes ]]; then
    echo "invalid selection"
  fi
  if [[ $3 -le $2 ]]; then
    echo "from is greater than to.."
  fi
  if [[ $3 -gt $2 ]] && [[ $3 -le $mboxes ]]; then
    echo "Lowering endpoint value"
    mboxes=$3
  fi
  if [[ $i -lt 0 ]]; then
    i=0
  fi
  # Main loop
	echo "Listing jboss backend service state from $[$i+1] to $mboxes"
  while [ $i -lt $mboxes ]
	do
		i=$[$i+1]
		echo ""
    echo "============"
    echo "Checking m$i"
    echo "============"
    ssh -o StrictHostKeyChecking=no -i $pkey root@m$i.jam.maguscloud.com 'ls -ld /jboss/standalone/deployments/*.*ed' | awk '{print $9}'
	done
	echo "Front end servers and API's"
	for i in {1..5}; do
    echo ""
    echo "==========="
    echo "Checking c$i"
    echo "==========="
    ssh -o StrictHostKeyChecking=no -i $pkey root@c$i.jam.maguscloud.com 'ls -ld /jboss/standalone/deployments/*.*ed' | awk '{print $9}'
  done
fi

# JBOSS STOP
if [ $1 == 'stop' ]; then
  i="1"
	 echo "Stopping all jboss backend services (not M1)"
   while [ $i -lt $mboxes ]
   do
     i=$[$i+1]
     echo ""
     echo "============"
     echo "Stopping m$i"
     echo "============"
     ssh -o StrictHostKeyChecking=no -i $pkey root@m$i.jam.maguscloud.com 'service jboss stop'
   done
fi

# JBOSS START
if [ $1 == 'start' ]; then
  i="1"
   echo "Start jboss on all backend servers (not M1)"
   while [ $i -lt $mboxes ]
   do
     i=$[$i+1]
     echo ""
     echo "============"
     echo "Starting m$i"
     echo "============"
     ssh -o StrictHostKeyChecking=no -i $pkey root@m$i.jam.maguscloud.com 'service jboss start'
   done
fi

# JBOSS SCRIPT
if [ $1 == 'script' ]; then
  i="1"
    echo "Usage: jb (start|stop)"
    echo "for i in {2..$mboxes}; do"
    echo 'ssh -i /auth/DQM-key.pem root@m$i.jam.maguscloud.com `service jboss (start|stop)`'
    echo "done"
	#for i in {2..38}; do ssh -i /mnt/magus/auth/CrownpeakDQM.pem root@in.m$i 'echo "Stopping jboss service on m'$i'"; service jboss stop' ; done
fi


# JBOSS RESTART
if [ $1 == 'restart' ]; then
  i="1"
    echo "Restarting jboss on all backend servers (not M1)"
    while [ $i -lt $mboxes ]
    do
      i=$[$i+1]
      echo ""
      echo "============"
      echo "Starting m$i"
      echo "============"
      ssh -o StrictHostKeyChecking=no -i $pkey root@m$i.jam.maguscloud.com 'service jboss stop && service jboss start'
    done
fi

# JBOSS SSH RESET
if [[ $1 == 'reset' ]] && [[ $2 == 'keys' ]]; then
  echo "Resetting all ssh keys"
  cd ~/.ssh
  dir=`pwd`
  cd -
  i=0
  while [ $i -lt $mboxes ]
    do
      i=$[$i+1]
      echo ""
      echo "============"
      echo "Checking m$i"
      echo "============"
      ssh-keygen -f "$dir/known_hosts" -R "m$i.jam.maguscloud.com"
    done
  exit 1;
fi

# JBOSS HELP
if [ $1 == 'help' ]; then
	clear
	echo "JBOSS service script v $version"
	echo "============================"
	echo ""
	echo "Options are:"
	echo "jb stop    - to stop jboss on all M servers, but not M1"
	echo "jb start   - to start jboss on all M servers, but not M1"
	echo "jb list    - to list all deployed versions in the standard deployments directory, for all servers"
	echo "jb restart - stops and restarts all jboss services from M2 to the end."
	echo "jb version - displays the version of the current script that you have installed."
	echo "jb help    - displays this help page."
	echo "jb script  - displays script execution details"
	echo "jb         - any other value ignored."
fi


exit;
